### ISSUE TITLE
Mutations called by Mutect2 in paired mode are not annotated by VEP

### ISSUE THREAD

**Issue by Janzulene** [nf-core/sarek#1679]
### Description of the bug

When using paired mode with Mutect2 to call mutations from both normal and tumor samples of the same patient, the resulting mutations are not annotated by VEP, despite VEP being specified in the tools parameters. It seems that the mutations are skipped during the annotation process. I would like to clarify whether this is intended behavior or if it constitutes a bug.

### Command used and terminal output

nextflow run /data/cache/nextflow/nf-core-sarek_3.4.2/3_4_2 -resume -offline -profile singularity -params-file configs/wes2_paired.yaml

### Relevant files

the used param file in above command:
```yaml
input:  'configs/wes2_paired.csv'
outdir: 'data/processed/WES2_20240816_paired'
tools:  'mutect2,vep'
wes:    true
step:   'variant_calling'

# reference genome
genome: null
igenomes_ignore: true
save_reference: true
fasta: "/data/genomes/alias/GRCm39_ensembl/fasta/110.20230421-sm-primary_assembly/GRCm39_ensembl.fa"
fasta_fai: "/data/genomes/alias/GRCm39_ensembl/fasta/110.20230421-sm-primary_assembly/GRCm39_ensembl.fa.fai"
# bwa: '/data/genomes/alias/GRCm39_ensembl/bwa_index/110.20230421-sm-primary_assembly-bwa_0.7.17'
vep_cache: '/data/cache/vep_cache'
vep_genome: 'GRCm39'
vep_species: 'mus_musculus'
vep_cache_version: 110
download_cache: false

snpeff_cache: '/data/cache/snpeff_cache'
snpeff_genome: 'GRCm38'
snpeff_db: 99

trim_fastq: true
save_mapped: true
save_output_as_bam: true

# resource
max_cpus: 32
max_memory: "192.GB"
```
